package com.example.smartreminder.data;

import android.content.Context;

import androidx.annotation.NonNull;
import androidx.room.Database;
import androidx.room.Room;
import androidx.room.RoomDatabase;
import androidx.room.TypeConverters;
import androidx.sqlite.db.SupportSQLiteDatabase;

import java.util.Date;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

@Database(entities = {User.class, Reminder.class, Category.class, ReminderLog.class, RecurrenceRule.class, Badge.class, UserBadge.class}, version = 6, exportSchema = false)
@TypeConverters({Converters.class})
public abstract class ReminderDatabase extends RoomDatabase {

    public abstract UserDao userDao();
    public abstract ReminderDao reminderDao();
    public abstract CategoryDao categoryDao();
    public abstract ReminderLogDao reminderLogDao();
    public abstract RecurrenceRuleDao recurrenceRuleDao();

    private static volatile ReminderDatabase INSTANCE;
    private static final int NUMBER_OF_THREADS = 4;
    public static final ExecutorService databaseWriteExecutor =
            Executors.newFixedThreadPool(NUMBER_OF_THREADS);

    public static ReminderDatabase getDatabase(final Context context) {
        if (INSTANCE == null) {
            synchronized (ReminderDatabase.class) {
                if (INSTANCE == null) {
                    INSTANCE = Room.databaseBuilder(context.getApplicationContext(),
                                    ReminderDatabase.class, "reminder_database")
                            .fallbackToDestructiveMigration()
                            .addCallback(sRoomDatabaseCallback)
                            .build();
                }
            }
        }
        return INSTANCE;
    }

    private static final RoomDatabase.Callback sRoomDatabaseCallback = new RoomDatabase.Callback() {
        @Override
        public void onCreate(@NonNull SupportSQLiteDatabase db) {
            super.onCreate(db);

            databaseWriteExecutor.execute(() -> {
                UserDao userDao = INSTANCE.userDao();
                ReminderDao reminderDao = INSTANCE.reminderDao();
                CategoryDao categoryDao = INSTANCE.categoryDao();

                // 1. Create System Admin (id will be autogenerated)
                User admin = new User("admin@example.com", "hash_123456", "System Admin", null, null);
                admin.setLevel(2);
                admin.setXp(150);
                admin.setCurrent_streak(4);
                userDao.insert(admin);
                
                // Note: Since id is autogenerated, we'd normally need to get the generated id back.
                // For dummy data, we assume this is the first user (id = 1).
                int adminId = 1;

                // 2. Create Default Categories
                Category cat1 = new Category(null, "Học tập");
                cat1.setIs_system(1);
                categoryDao.insert(cat1);

                Category cat2 = new Category(null, "Cá nhân");
                cat2.setIs_system(1);
                categoryDao.insert(cat2);

                // 3. Create Demo Reminders
                long today = System.currentTimeMillis();
                Reminder task1 = new Reminder(adminId, "Study Android", new Date(today), new Date(today));
                task1.setStatus("done");
                task1.setCategory_id(1);
                reminderDao.insert(task1);

                reminderDao.insert(new Reminder(adminId, "Buy groceries", new Date(today), new Date(today)));
                reminderDao.insert(new Reminder(adminId, "Team meeting", new Date(today), new Date(today)));
                reminderDao.insert(new Reminder(adminId, "Gym session", new Date(today), new Date(today)));
                reminderDao.insert(new Reminder(adminId, "Read a book", new Date(today), new Date(today)));
            });
        }
    };
}
