package com.example.smartreminder.data;

import android.content.Context;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.room.Database;
import androidx.room.Room;
import androidx.room.RoomDatabase;
import androidx.room.TypeConverters;
import androidx.sqlite.db.SupportSQLiteDatabase;

import com.example.smartreminder.data.badge.Badge;
import com.example.smartreminder.data.badge.BadgeDao;
import com.example.smartreminder.data.category.Category;
import com.example.smartreminder.data.category.CategoryDao;
import com.example.smartreminder.data.recurrencerule.RecurrenceRule;
import com.example.smartreminder.data.recurrencerule.RecurrenceRuleDao;
import com.example.smartreminder.data.reminder.Reminder;
import com.example.smartreminder.data.reminder.ReminderDao;
import com.example.smartreminder.data.reminderlog.ReminderLog;
import com.example.smartreminder.data.reminderlog.ReminderLogDao;
import com.example.smartreminder.data.user.User;
import com.example.smartreminder.data.user.UserDao;
import com.example.smartreminder.data.userbadge.UserBadge;
import com.example.smartreminder.data.userbadge.UserBadgeDao;

import java.util.Date;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

@Database(entities = {User.class, Reminder.class, Category.class, ReminderLog.class, RecurrenceRule.class, Badge.class, UserBadge.class}, version = 6, exportSchema = false)
@TypeConverters({Converters.class})
public abstract class ReminderDatabase extends RoomDatabase {

    public abstract UserDao userDao();
    public abstract ReminderDao reminderDao();
    public abstract CategoryDao categoryDao();
    public abstract ReminderLogDao reminderLogDao();
    public abstract RecurrenceRuleDao recurrenceRuleDao();
    public abstract BadgeDao badgeDao();
    public abstract UserBadgeDao userBadgeDao();

    private static volatile ReminderDatabase INSTANCE;
    private static final int NUMBER_OF_THREADS = 4;
    public static final ExecutorService databaseWriteExecutor =
            Executors.newFixedThreadPool(NUMBER_OF_THREADS);

    public static ReminderDatabase getDatabase(final Context context) {
        if (INSTANCE == null) {
            synchronized (ReminderDatabase.class) {
                if (INSTANCE == null) {
                    INSTANCE = Room.databaseBuilder(context.getApplicationContext(),
                                    ReminderDatabase.class, "reminder_database")
                            .fallbackToDestructiveMigration()
                            .addCallback(sRoomDatabaseCallback)
                            .build();
                }
            }
        }
        return INSTANCE;
    }

    private static final RoomDatabase.Callback sRoomDatabaseCallback = new RoomDatabase.Callback() {
        @Override
        public void onCreate(@NonNull SupportSQLiteDatabase db) {
            super.onCreate(db);

            databaseWriteExecutor.execute(() -> {
                int testUserId = 1;
                UserDao userDao = INSTANCE.userDao();
                ReminderDao reminderDao = INSTANCE.reminderDao();
                CategoryDao categoryDao = INSTANCE.categoryDao();
                RecurrenceRuleDao recurrenceRuleDao = INSTANCE.recurrenceRuleDao();
                BadgeDao badgeDao = INSTANCE.badgeDao();
                UserBadgeDao userBadgeDao = INSTANCE.userBadgeDao();
                ReminderLogDao logDao = INSTANCE.reminderLogDao();
                // 1. Create System Admin (id will be autogenerated)
                User admin = new User("admin@example.com", "hash_123456", "System Admin", null, null);
                admin.setLevel(2);
                admin.setXp(150);
                admin.setCurrent_streak(4);
                userDao.insert(admin);
                // 1. Insert Categories (Yêu cầu: user_id, name)
                categoryDao.insert(new Category( "work"));
                categoryDao.insert(new Category( "health"));
                categoryDao.insert(new Category( "shopping"));


                // 2. Insert Recurrence Rules (Yêu cầu: user_id, frequency, start_date)
                recurrenceRuleDao.insert(new RecurrenceRule( "daily", new Date()));
                recurrenceRuleDao.insert(new RecurrenceRule( "weekly", new Date()));

                // 3. Insert Reminders (Yêu cầu: user_id, title, due_date, remind_at)
                Date now = new Date();
                // Tạo đối tượng trước rồi mới set CategoryId nếu cần
                Reminder r1 = new Reminder(testUserId,1, "Project Planning", now, now);
                r1.setCategory_id(1);
                reminderDao.insert(r1);

                Reminder r2 = new Reminder(testUserId,2, "Workout", now, now);
                r2.setCategory_id(2);
                reminderDao.insert(r2);

                // 4. Insert Badges (Yêu cầu: name, description, xp_reward)

                long b1 = badgeDao.insert(new Badge("new guy", "complete 1 task", 10));
                long b2 = badgeDao.insert(new Badge("hard worker", "completed 7 days straight", 50));

                // 5. User Badge (Yêu cầu: user_id, badge_id, earned_at)

                userBadgeDao.insert(new UserBadge(testUserId, (int)b1, new Date()));
                userBadgeDao.insert(new UserBadge(testUserId, (int)b2, new Date()));

                // 6. Reminder Log (Yêu cầu: reminder_id, user_id, action, actioned_at)

                logDao.insert(new ReminderLog(1, testUserId, "completed", new Date()));

            });
        }
    };
}
